### PR TITLE
Use local ./tmp directory for testing

### PR DESCRIPTION
**Pull request by antstorm**
Hey,

I'm trying to integrate this repo with TravisCI for continuous integration and the first issue I came up with is being unable to use global `/tmp` for hosting a test samba server. So this change moves it to local `./tmp` directory, while also cleaning it up after each run (otherwise some files are left in there in between runs).

### CODE REVIEW

**Comment by johnae** [comment]
I'll take a look today.

**Comment by johnae** [comment]
@antstorm Please see latest master.

**Comment by johnae** [comment]
@antstorm By the way I've added Circle CI support to the repo. For some reason the specs are ridiculously slow on CircleCI but they do pass. Not sure why they're so slow.

**Comment by antstorm** [comment]
@johnae despite the fact that you went with CircleCI, I think this is still a viable change, because current specs leave some files hanging in global `/tmp` which is a very bad thing.

**Pull request closed without merging**
