### PR TITLE
Update RSpec to the new version

### PR DESCRIPTION
**Pull request by antstorm**
Hi,

Here's a PR that upgrades RSpec to the new version, plus all the assertions rewritten to use new "expect" syntax.

This one probably doesn't need a gem release, since it's dev-only change.

### CODE REVIEW

**Comment by johnae** [comment]
Sorry for the slow response. Will look at this today.

**Comment by antstorm** [comment]
@johnae no worries, ping me if you've got any comments

**Comment by johnae** [comment]
@antstorm Are you running the spec suite and is it green?

**Comment by antstorm** [comment]
@johnae yes, all green, is that not the case for you?

**Comment by johnae** [comment]
@antstorm What OS are you on? Linux here, used to be OS X. Think it's a config issue with samba.

**Comment by antstorm** [comment]
@johnae I'm on OS X. Any particular output you're getting?

**Comment by johnae** [comment]
@antstorm Switched to Linux a year or so ago. Haven't really used sambal in some time. Further along here now, no complaints from samba anymore (and I've got stuff running off of a directory directly under project root). Still, most specs fail. At work now so I can't really investigate further atm. Will look at it later.

**Comment by johnae** [comment]
@antstorm Please see latest master.

**Comment by antstorm** [comment]
@johnae that's not very collaborative. I think I'm done with this repo, good luck!

**Pull request closed without merging**
