### PR TITLE
Parse files to array

### PR DESCRIPTION
**Pull request by nextgenappsllc**
Returns directory contents as an array and adds hidden tag. Also supports file names with multiple spaces in a row

### CODE REVIEW

**Comment by nextgenappsllc** [comment]
I was running into a problem where names with more than 2 spaces in them were coming out in correct. Also there are times when a directory is named the same as an extensionless file and therefore it would only show one of them in the hash as opposed to an array. Additionally I needed to hide hidden files from users so I was removing any file with certain prefixes like ~ or $ which non hidden files can be named with. I'm using this to connect to Windows shares from a Linux machine. I'm not sure if the regex will catch non English time stamp formats

**Comment by johnae** [comment]
I'll take a look tomorrow.

**Comment by johnae** [comment]
Seems to be a problem with running the specs. It's not related to this pull request but rather changes in smbd. In general I guess these additions are fine but I'd like to see specs for them. I'll have to look into why we can't start smbd any longer. Anyone is welcome to take a look at this ofc. I'm quite busy at work so it may be some time until I get around to this.

I did some testing and it seems to be because of changes in samba. For one thing, smbd no longer takes the same options. There's also the annoying problem with the core dump directory. Tried disabling it without success. Though I only spent 5-10 minutes on this now.

**Comment by johnae** [comment]
Could you add a spec to this?

**Comment by johnae** [comment]
Closing since there's been no response.

**Pull request closed without merging**
