### PR TITLE
Split Client & Response classes into separate files

### PR DESCRIPTION
**Pull request by antstorm**
Hi,

Here's some tidying of the `sambal.rb` files. I've moved `Client` and `Response` out into separate files and removed some of the `require`s that don't seem to be used at all.

### CODE REVIEW

**Comment by johnae** [comment]
@antstorm Would need to be fixed before merging to latest master. Thanks!

**Comment by antstorm** [comment]
@johnae what needs to be fixed? Did you mean "rebased"?

**Comment by johnae** [comment]
@antstorm Yeah a rebase and possibly some rework would be needed I think.

**Comment by antstorm** [comment]
Rebased and reopened: #19

**Pull request closed without merging**
